---
title: "Daily Exercise 17-19"
author: "Yan Wang"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(sf)
library(tidyverse)
library(elevatr)
library(rgdal)
library(readr)
library(raster)
library(osmdata)
library(leaflet)
```

```{r message=FALSE, warning=FALSE}
uscities <- read_csv("~/github/geog-176A-labs/data/uscities.csv") %>%
  st_as_sf(coords = c("lng", "lat"), crs = 4326) %>% 
  filter(city == "Goleta") %>% 
  st_transform(5070) %>% 
  st_buffer(5000) %>% 
  st_bbox() %>% 
  st_as_sfc() %>% 
  st_as_sf()

elev = elevatr::get_elev_raster(uscities, z = 11) %>% 
  raster::crop(uscities)
plot(elev)
```
###Describe the properties:
```{r}
elev
```

Daily Exercise 17

```{r}
threshold = function(x) {ifelse(x <= 0 , NA, 1)}
threshold(100)
```
```{r}
threshold(-100)
```
```{r}
elev2 = calc(elev, threshold)
plot(elev2, col = viridis::viridis(256))
```

```{r}
elev3 = elev * elev2
plot(elev3, col = viridis::viridis(256))
```
```{r}
rcl = data.frame(min = seq(0,500,100),max =  seq(100,600,100), lab = c(0:5))
rc = reclassify(elev3, rcl, include.lowest=TRUE)
s = stack(elev, elev2, elev3, rc) %>% 
  setNames(c("Elevation", "Mask", "Terrain", "Topography"))
plot(s, col = viridis::viridis(256))
```

```{r message=FALSE, warning=FALSE}
bb  = st_bbox(s) %>% 
  st_as_sfc() %>% 
  st_transform(4326)
osm = osmdata::opq(bb) %>% 
  add_osm_feature(key = 'amenity', value = "restaurant") %>% 
  osmdata_sf()
print(osm)
```
```{r message=FALSE, warning=FALSE}
restaurant = osm$osm_points %>% 
   filter(name != 'NA')
restaurant = restaurant %>% 
   mutate(elevation = raster::extract(elev, restaurant))
labels = restaurant %>% 
  dplyr::select(elevation)
leaflet() %>% 
  addProviderTiles(providers$CartoDB) %>% 
  addMarkers(data = restaurant, popup = leafpop::popupTable(st_drop_geometry(labels), feature.id = F, row.numbers = F), label = ~name)
```

